services:
  # Backend Service
  - type: web
    name: expense-manager-backend
    env: node
    repo: https://github.com/12-Divyansh/expense-manager-mern.git
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: PORT
        value: 10000

  # Frontend Service
  - type: web
    name: expense-manager-frontend
    env: static
    repo: https://github.com/12-Divyansh/expense-manager-mern.git
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://expense-manager-backend.onrender.com
